### PR TITLE
fixing video uploads

### PR DESCRIPTION
**Pull request by ravimisra**
Fixed the issue related to posting a video post on Tumblr.
A video post can be uploaded as follows:
```php
$client = new Tumblr\API\Client($consumerKey, $consumerSecret);
$client->setToken($token, $tokenSecret);
$post_data = array('type' => 'video',  'caption' => 'this is a test video', 'data' => $path_of_video_file);
$createPost = $client->createPost($blog, $post_data);
```

### CODE REVIEW

**Comment by grzegorz-pierzakowski** [comment]
Merge this please

**Comment by KrishnaVishwakarma1595** [comment]
@ravimisra I'm not able to post a video even replacing the code with your updated code. Here is my code:

$client->setToken($accessToken, $accessSecret);
	        $res = $client->createPost('my-blog-name-goes-here', array(
	            'type' => 'video', 
	            'caption' => $text,
	            'data' =>$path, // path is like the url of video I've uploaded
	        ));

I tried giving the root path to the directory where the video will save, but not working. 
Getting this response everytime - 

Fatal error: Uncaught Tumblr\API\RequestException: [400]: Bad Request thrown in /var/www/project/lib/tumblr-api/vendor/tumblr/tumblr/lib/Tumblr/API/Client.php on line 427

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by ravimisra** [comment]
> Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks!

Accepted terms at https://yahoocla.herokuapp.com/, please merge.

**Comment by ravimisra** [comment]
@KrishnaVishwakarma1595, $path should be initialized to the filename of the video file with absolute path. e.g. /tmp/video/my_video_file_to_upload.mp4

**Comment by KrishnaVishwakarma1595** [comment]
@ravimisra Thanks for your reply. I've tried giving absolute path also but it's still giving the same error.

$client->setToken($accessToken, $accessSecret);
$res = $client->createPost('my-blog-name-goes-here', array(
'type' => 'video',
'caption' => $text,
'data' =>$path, // path is like '/var/www/project/uploads/files/video_file.mp4
));

**Comment by sndsgd** [comment]
@ravimisra We ended up patching this issue on the backend some time ago. I just re-tested, and was able to create a video file without issue using the following snippet (sensitive information replaced with `...`):

```php
<?php

require __DIR__ . "/vendor/autoload.php";

const CONSUMER_KEY = "...";
const CONSUMER_SECRET = "...";
const ACCESS_TOKEN = "...";
const ACCESS_TOKEN_SECRET = "...";
const BLOG = "...";

$video_file = getenv("HOME") . "/Downloads/video.mp4";

$client = new Tumblr\API\Client(CONSUMER_KEY, CONSUMER_SECRET);
$client->setToken(ACCESS_TOKEN, ACCESS_TOKEN_SECRET);
$post_data = ["type" => "video",  "caption" => "this is a test video", "data" => $video_file];

try {
    print_r($client->createPost(BLOG, $post_data));
} catch (Exception $ex) {
    print_r($ex);
}
```

Please feel free to create an issue if you still run into problems posting videos.

**Comment by himanshupatel95** [comment]
Video Not Upload issue . Error status 401

require __DIR__ . "/vendor/autoload.php";

const CONSUMER_KEY = "...";
const CONSUMER_SECRET = "...";
const ACCESS_TOKEN = "...";
const ACCESS_TOKEN_SECRET = "...";
const BLOG = "12345678";

$video_file = "../video.mp4";

$client = new Tumblr\API\Client(CONSUMER_KEY, CONSUMER_SECRET);
$client->setToken(ACCESS_TOKEN, ACCESS_TOKEN_SECRET);
$post_data = ["type" => "video",  "caption" => "this is a test video", "data" => $video_file];

try {
    print_r($client->createPost(BLOG, $post_data));
} catch (Exception $ex) {
    print_r($ex);
}

**Comment by sndsgd** [comment]
@himanshupatel95 If you're getting responses with a `401` status code, that means we could not find a user for the provided access token and access token secret.

Please go to https://api.tumblr.com/console to create a new access token and give that a shot.

**Comment by himanshupatel95** [comment]
> @himanshupatel95 If you're getting responses with a `401` status code, that means we could not find a user for the provided access token and access token secret.
> 
> Please go to https://api.tumblr.com/console to create a new access token and give that a shot.

Thanks

**Pull request closed without merging**
