### PR TITLE
Updated Travis badge to svg for waaay better quality

### PR DESCRIPTION
**Pull request by lfarah**

### CODE REVIEW

**Comment by sndsgd** [comment]
👍

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by komapa** [comment]
@lfarah, please sign the CLA if you want to see this PR merged :)

**Comment by AkgunFatih** [comment]
you are wasting your time here, tumblr doesnt care about updating there api and there customers

**Pull request merged**
